In [2]:
import numpy as np 

## 1 Creating the Array

In [4]:
arr = np.array([1,2,3,4,5])

## 2 To See the output of the array

In [5]:
arr

array([1, 2, 3, 4, 5])

## 3 To Check the type of the array 
   ###  *(dype) Attribute is use to check the type of the array

In [6]:
arr.dtype

dtype('int64')

## 4 . Vectorization

##  -- * To perform the operation on each value in the array

In [7]:
arr1 = np.array([1,2,3,4])
arr2= np.array([6,7,8,9])

In [8]:
arr3 = arr1+arr2
arr3

array([ 7,  9, 11, 13])

In [9]:
arr1

array([1, 2, 3, 4])

In [10]:
arr2

array([6, 7, 8, 9])

In [11]:
arr2//2

array([3, 3, 4, 4])

# 5 Difference Between Array & List 
    

## i> List code 

In [12]:
%%time
list1= [x for x in range(1,1001)]
list2= [x for x in range(2001,3001)]
list3 = []
for i in range(len(list1)):
    list3.append(list1[i]+list2[i])

CPU times: total: 0 ns
Wall time: 544 μs


## ii> Array Code

In [13]:
%%time
array1 = np.array([x for x in range(1,1001)])
array2 = np.array([x for x in range(2001,3001)])
array3 = array1+array2

CPU times: total: 0 ns
Wall time: 340 μs


In [14]:
array3.dtype

dtype('int64')

# Multidimentional array

In [15]:
arr1 = np.array([[1,2,3,4],[5,6,7,8]])
arr1

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [16]:
arr = np.array([[[1,2],
                 [3,4]],
                [[5,6],
                [7,8]]])

In [17]:
arr1.shape

(2, 4)

# Brodcating

In [18]:
arr1= np.array([[10,20,30,40],
                [50,60,70,80]])
arr2 = np.array([1,2,3,4])

In [19]:
arr3= arr1+arr2
arr3

array([[11, 22, 33, 44],
       [51, 62, 73, 84]])

In [20]:
arr2 = np.pad(arr2,(0,4))

In [21]:
arr2

array([1, 2, 3, 4, 0, 0, 0, 0])

In [22]:
list1 = [10,45,67]
arr1 = np.array(list1)
list1
# List to array

[10, 45, 67]

In [23]:
t1 = (1,2,3)
arr1 =np.array(t1)
arr1
#Tuple to array 

array([1, 2, 3])

In [24]:
d1 = {1,3,4,5}
arr1 = np.array(d1)
arr1 
# set  to array

array({1, 3, 4, 5}, dtype=object)

In [25]:
arr1.size

1

## It create the number between 1 to 11

In [26]:
arr1 = np.arange(1,11)
arr1

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

## it create the number between 1 to 11 step between 2 

In [27]:
arr1 = np.arange(1,11,2)
arr1

array([1, 3, 5, 7, 9])

# it ganerate the random number

In [28]:
arr1 = np.random.randint(1,50,5)
arr1 
# it ganerate the random number

array([22, 42, 23, 46, 33], dtype=int32)

In [29]:
arr1 = np.linspace(1,20,5)
arr1

array([ 1.  ,  5.75, 10.5 , 15.25, 20.  ])

## Ganerate the random number between 0 ,1

In [30]:
arr1 = np.random.rand(10)
arr1

array([0.7570591 , 0.51916071, 0.50935193, 0.18776066, 0.70223922,
       0.19675836, 0.88026584, 0.13194165, 0.18556812, 0.73176888])

## Creating the array with value 0 in 5 times

In [31]:
arr = np.zeros(5)
arr

array([0., 0., 0., 0., 0.])

## Creating the array that only store the 1 value for 10 times

In [32]:
arr = np.ones(10)
arr

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

## Create a identity matrix

In [33]:
arr = np.eye(4)
arr

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

## Methods in the array

    ## 1 > reshape() Method
    ## it convert the 1d array in 2d array or multi dymentional array 
    ## Ex :

In [3]:
a1 = np.array([1,2,3,4,5])
a1

array([1, 2, 3, 4, 5])

# Methods are
    ## 1> reshape() it convert the 1D array shape in to 2d or multi D 
    ## 2> max() it return the maximum value in the array
    ## 3> min() it return the  small/ minimum  value in the array
    ## 4> argmin() it return the index of the minimum value in the array
    ## 5> argmax() it return the index of the maximum value in the array
    ## 6> sum()  it return the sum of the array elements in the array

# Example one by one

## 1> reshape() Method

In [6]:
a1.reshape(5,1)

array([[1],
       [2],
       [3],
       [4],
       [5]])

## 2> max() Method

In [8]:
a1.max()

np.int64(5)

## 3> Min() Method

In [9]:
a1.min()

np.int64(1)

## 4>argmax() Method

In [10]:
a1.argmax()

np.int64(4)

## 5> argmin() Method

In [11]:
a1.argmin()

np.int64(0)

## 6> sum() Method 

In [13]:
a1.sum()

np.int64(15)

## axis =1 it used to get minimum value from each and every row in the array
## axis =0 it used to get minimum value from each and every column in the array

# axis =1 - minimum  value from all row
# axis =0  minimum value from all column

In [19]:
a1 = np.array([
    [1,21,2,45,22,56,5],
    [89,34,63,23,14,6,0]   # added 0
])
a1


array([[ 1, 21,  2, 45, 22, 56,  5],
       [89, 34, 63, 23, 14,  6,  0]])

In [20]:
a1.min(axis=1)


array([1, 0])

In [21]:
a1.min(axis=0)

array([ 1, 21,  2, 23, 14,  6,  0])

# Selection / indexing
  ## Indexing always start from zero

## (To accessing the number using indexing)

In [23]:
a1[1]

array([89, 34, 63, 23, 14,  6,  0])

In [24]:
a1[0:1]

array([[ 1, 21,  2, 45, 22, 56,  5]])

In [25]:
a1


array([[ 1, 21,  2, 45, 22, 56,  5],
       [89, 34, 63, 23, 14,  6,  0]])

In [26]:
a1[0:2]

array([[ 1, 21,  2, 45, 22, 56,  5],
       [89, 34, 63, 23, 14,  6,  0]])

IndexError: index 3 is out of bounds for axis 0 with size 2

In [28]:
a1//2

array([[ 0, 10,  1, 22, 11, 28,  2],
       [44, 17, 31, 11,  7,  3,  0]])

## To get the even from an array with the help of conditional slicing

In [29]:
a1[a1%2==0]

array([ 2, 22, 56, 34, 14,  6,  0])

## To get the element in the array is <50 using the conditional slicing

In [30]:
a1[a1<50]

array([ 1, 21,  2, 45, 22,  5, 34, 23, 14,  6,  0])

## To get the element is >50 and even number

In [31]:
a1[(a1>50) & (a1%2==0)]

array([56])